### ISSUE TITLE
jupyterlab_vim

### ISSUE THREAD

**Issue by matt-long** [NCAR/ncar-python-tutorial#42]
Can we add https://github.com/jwkvam/jupyterlab-vim to `post_build_base`? 

cc @brittstephens

**Comment by kmpaul** [comment]
If this gets installed, does this automatically change the key bindings for jupyterlab?  Or is it something you can opt in/out?

**Comment by matt-long** [comment]
@brittstephens, do you know the answer?

**Comment by kmpaul** [comment]
I've done some research on this.  JupyterLab extensions are enabled at installation time.  So, this would change the behavior for everyone, which is not desired.

You _could_ install this extension and then disable it with:

```bash
jupyter labextension disable jupyterlab_vim
```

But then you'd have to go to the command line and execute:

```bash
jupyter labextension enable jupyterlab_vim
```

to enable it.  However, requiring this is not much different than having the user install the extension themself.  There are differences, though, which I enumerate below.

**If you Install the extension and disable it, requiring the user enable it before use:**

1. the application (`jupyter`) does not need to be rebuilt when enabling the extension,
2. whether it is enabled or disabled, it can conflict with other extensions that a use might install, and
3. the user must execute the enable command from the command line.

**If you require the user install the extension themself:**

1. the extension is downloaded and the application (`jupyter`) is rebuilt, albeit automatically,
2. there is minimal risk of creating conflicts for users who choose not to use the extension, and
3. the extension can be installed via the JupyterLab extension manage (from within the browser UI), without needing to execute any command-line commands.

Personally, I think that it makes sense _not_ to install it and let users install it themselves.


The only advantage that I can see to doing this, rather than just asking the user to install the extension themselves (which they can do through JupyterLab's extension manager in the browser
